// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Identifies emerging product trends by analyzing real-time data.
 *
 * - identifyEmergingTrends - A function that initiates the trend identification process.
 * - IdentifyEmergingTrendsInput - The input type for the identifyEmergingTrends function.
 * - IdentifyEmergingTrendsOutput - The return type for the identifyEmergingTrends function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifyEmergingTrendsInputSchema = z.object({
  salesData: z
    .string()
    .describe('Real-time sales data, including product sales volume and revenue.'),
  socialMediaEngagement: z
    .string()
    .describe(
      'Social media engagement metrics, including likes, shares, comments, and mentions.'
    ),
  searchTrends: z
    .string()
    .describe('Search trends data, including search volume and related keywords.'),
});
export type IdentifyEmergingTrendsInput = z.infer<
  typeof IdentifyEmergingTrendsInputSchema
>;

const IdentifyEmergingTrendsOutputSchema = z.object({
  trendAnalysis: z
    .string()
    .describe('Analysis of emerging product trends and their potential viability.'),
  productRecommendations: z
    .string()
    .describe('Recommended products based on the trend analysis.'),
});
export type IdentifyEmergingTrendsOutput = z.infer<
  typeof IdentifyEmergingTrendsOutputSchema
>;

export async function identifyEmergingTrends(
  input: IdentifyEmergingTrendsInput
): Promise<IdentifyEmergingTrendsOutput> {
  return identifyEmergingTrendsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'identifyEmergingTrendsPrompt',
  input: {schema: IdentifyEmergingTrendsInputSchema},
  output: {schema: IdentifyEmergingTrendsOutputSchema},
  prompt: `You are an expert in identifying emerging product trends. Analyze real-time sales data, social media engagement, and search trends to determine product viability.

Sales Data: {{{salesData}}}
Social Media Engagement: {{{socialMediaEngagement}}}
Search Trends: {{{searchTrends}}}

Based on this data, identify emerging product trends and recommend potential products.`,
});

const identifyEmergingTrendsFlow = ai.defineFlow(
  {
    name: 'identifyEmergingTrendsFlow',
    inputSchema: IdentifyEmergingTrendsInputSchema,
    outputSchema: IdentifyEmergingTrendsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
